### ISSUE TITLE
How to use in code

### ISSUE THREAD

**Issue by ssamikk** [vvaldersteins/ngx-svg#1]
Can I use the standard functions of the library SVG.js to dynamically create svg.
Or is the creation of svg elements provided only from the component template?

**Comment by vvaldersteins** [comment]
Hi ssamikk!

You can currently use the elements that are provided, but if you need any specific element added to the library, please, let me know.

**Comment by ssamikk** [comment]
Sorry for my English. Google translator helps me in this))
A small example interests me. How to dynamically create two pictures and mask them without using the html template

**Comment by ssamikk** [comment]
Something like that
`this.draw = SVG().addTo('#canvas').viewbox(0, 0, 300, 140);
 var text = this.draw.text('ABCDE');`

**Comment by vvaldersteins** [comment]
Did you checked the [demo](https://vvaldersteins.github.io/ngx-svg/) ? It has some examples, also for the texts and images. In additional, it contains documentation on how to add it to your Angular project. If you would create an image of how you would like your end-result to look like, I might be able to provide more information.

**Comment by ssamikk** [comment]
Thanks for the answer.
Your demo helped.

**Comment by ssamikk** [comment]
svg.filter.js - Whether prompt there is an opportunity of work with filters. In the demo did not find it.

**Comment by ssamikk** [comment]
It is not clear how to work with masks.
I need something like this svg:
`<svg>
<defs>
	<filter id="Sjuxub4g117" filterUnits="userSpaceOnUse">
		<feColorMatrix type="saturate" values="0"></feColorMatrix>
	</filter>
	<mask id="maskSjuxub4g196">
		<image xlink:href="images/SVG/favicon.svg" preserveAspectRatio="none" x="33" y="32" width="31" height="32"></image>
	</mask>
</defs>
<rect x="417" y="112" width="31" height="32" id="obj41" fill="#ff0000" mask="url('#maskSjuxub4g196')" style="fill-opacity: 0.5;"></rect>
</svg>`

**Comment by vvaldersteins** [comment]
Hi ssamikk!

Masks are not yet available. Regarding 3rd party extensions for svg, they are not available as well. I'll add it to my timeline, and will update you here, when they are updated.

**Comment by ssamikk** [comment]
Thanks for the answer.

**Comment by raminarmanfar** [comment]
There is no sample to show how to append custom css classes to the shapes. I need to border rectangle. When I add `classes=['rectClass']` it is not affected.

**Comment by vvaldersteins** [comment]
Hi there.

Please let me know if this issue is still happening. It might be that you are trying to set `border` css property instead of `stroke`. SVG does not support `border`, so give a try setting `stroke`. Also, instead of assigning `classes=['rectClass']`, try assigning the following `[classes]="['rectClass']"`.
