### ISSUE TITLE
How to align the image to the left [FEATURE]

### ISSUE THREAD

**Issue by oduvanka** [vvaldersteins/ngx-svg#12]
**Is your feature request related to a problem? Please describe.**
I added "viewBox" to the svg-container. Image is scaled down, centered.
How to align the image to the left?

**Describe the solution you'd like**
I want to use `preserveAspectRatio="xMinYMin meet"`
[preserveAspectRatio](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio)

**Additional context**
![preserveAspectRatio](https://user-images.githubusercontent.com/45239739/78082557-08fbff80-73bc-11ea-8796-a8007d15f9e1.PNG)

**Comment by vvaldersteins** [comment]
Do you want it to be left aligned with white space on the right side or do you want it to take the whole plot without any white spaces? Would be nice a screenshot indicating end result that you would like to achieve.

Please add also demo against which I could test it out.

**Comment by oduvanka** [comment]
@vvaldersteins 
I want it to be left aligned.  It will be great if it is without white spaces.
![4](https://user-images.githubusercontent.com/45239739/78163522-2d55eb80-7451-11ea-86aa-e78df9aad478.jpg)

[demo](https://oduvanka.github.io/checkered-notebook/)
[code](https://github.com/oduvanka/checkered-notebook/tree/master/src/app/draw)

**Comment by vvaldersteins** [comment]
I just checked the code, and it seems like your `viewBoxCanvas` `realModelWidth` calculation is wrong for the 2nd drawing. To achieve the result you should set it to 810. Basically the rulers on the top and bottom indicates the width of the viewbox that you should set to make it full-width. Same goes with the left and right sidebar rulers for the height.

**Comment by oduvanka** [comment]
@vvaldersteins 
wow!!!
Thank you very much, problem solved!)
wow! wow! wow! ))
