### ISSUE TITLE
[FEATURE] SVG element nesting support

### ISSUE THREAD

**Issue by ninja65** [vvaldersteins/ngx-svg#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ninja65** [comment]
It would be appreciated if the svg elements currently supported allowed nesting. It is not possible at the moment. For example : <svg-rect><svg-text></svg-text></svg-rect>

**Comment by vvaldersteins** [comment]
Hi ninja! 

Could you give some more information of what you would like to achieve? It seems that the example you wanted to mention is not visible.

**Comment by ninja65** [comment]
Hi Valters,

So it would be nice, for example, if the following construction worked :
<svg-rect     >

                                         <svg-text/>

                                         <svg-image/>

                                    </svr-rect>

I tried it and did not work. Worked in a way, bacause the text were
displayed, but the positions did not consider the encapsulating element as
I expected.

I have another question: can you send me an example to see how the css
classes have to be specified for a text? I have the following simple
class:
.boldtext {
      font-weight: bold;
    }

defined in the component.css file and i would like to apply it to a text
element.

Best regards,
Csaba Hajdu

**Comment by vvaldersteins** [comment]
Hi Csaba!

Regarding the encapsulation, for now you can manually position the elements in the way that you would like them to appear using the `x` and `y` position attributes.

For the classes, you just add all classes that you would like to apply for a specific element in an array and pass it into `classes` property. For example -

```
<svg-text [text]="'Hello world'" [classes]="cssClasses"></svg-text>
```

and in your component.ts file -

```
....
public cssClasses = ['boldtext'];
```

**Comment by vvaldersteins** [comment]
Closing due to no response, assuming this issue was solved.
