### ISSUE TITLE
[FEATURE] Allow relative units for positioning

### ISSUE THREAD

**Issue by Thomas1664** [vvaldersteins/ngx-svg#22]
**Is your feature request related to a problem? Please describe.**
I want to center text horizontally but if I set x to 50%, the value resets to 0.

**Describe the solution you'd like**
Ether allow strings as well or create an input to specify the unit.

**Comment by vvaldersteins** [comment]
This seems to be an issue with actual root library. I've created a ticket for svg.js, and after they have provided the fix, will update the library accordingly.

Thanks for spotting it!

**Comment by vvaldersteins** [comment]
I got a response from the `svg.js` library. The text element does not accept string inputs by default. If you would like to calculate percentage, you would have to dynamically calculate the parent container width / height and then accordingly calculate 50% of it and assign the value as numeric value.

Closing this issue.
