### ISSUE TITLE
Angular 10 not yet integrated smoothy

### ISSUE THREAD

**Issue by sllegendre** [vvaldersteins/ngx-svg#32]
**Problem**
Does not install smoothly with angular 10, because it requires a peer of angular 9.

**To Reproduce**
1. Make an angular 10 project
2. Try to use ngx-svg as described in README

**Expected behavior**
works.

Instead:
You get an "npm WARN … requires a peer of … but none is installed. You must install ..."
with a peer requirement of angular 9.

**Comment by vvaldersteins** [comment]
Hi! Thanks for creating the issue. I've upgraded the library, now the latest version uses Angular v11 and all other dependencies were upgraded as well. Please give it a try.
