### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by hessam963** [vvaldersteins/ngx-svg#4]
canI draw line by mouse event the same as a svg.js ?
var draw = SVG('drawing').size(300, 300)
var rect = draw.rect(100, 100).attr({ fill: '#f06' })

**Comment by vvaldersteins** [comment]
Hi there! How do you mean draw a line by mouse event? Do you have a working example in svg.js?

**Comment by vvaldersteins** [comment]
The **svg-container**  has `hoverable` property and `clickEvent` event emitter. If you add both, then you should see a dot upon mouse hover of the container and upon clicking, you should get `x` and `y` coordinates of clicked position. Using those, you should be able to add line to the container.

If this does not solve the issue, please create another issue with more detailed explanation. Closing this one.
