### ISSUE TITLE
Classes are not applied to the circle [BUG]

### ISSUE THREAD

**Issue by oduvanka** [vvaldersteins/ngx-svg#7]
**Describe the bug**
I add custom classes to the circle, but I don't see changes

**To Reproduce**
1. I add custom classes "test1" and "test2" in the draw.component.css
[https://github.com/oduvanka/checkered-notebook/blob/error-classes/src/app/draw/draw.component.css](url)
2. I create `public myClasses: string[]` and initialized `this.myClasses = ['test1']` in the draw.component.ts
[https://github.com/oduvanka/checkered-notebook/blob/error-classes/src/app/draw/draw.component.ts#L35](url)
3. I add attr `<svg-circle ... [classes]="myClasses" ... ></svg-circle>` in the draw.component.html
[https://github.com/oduvanka/checkered-notebook/blob/error-classes/src/app/draw/draw.component.html#L25](url)
4. I do not see changes in the browser :(

**Expected behavior**
I expected the circles to have a stroke

**Desktop**
 - OS: Ubuntu 18 / Windows 8
 - Browser: Google Chrome
 - Version: 75.0.3770.142 (x64)

**Additional context**
Angular 8

**Comment by vvaldersteins** [comment]
Hi @oduvanka .

You need to use `::ng-deep` flag. See this for reference.

You can update your css to the following -

```
  ::ng-deep .test1 {
    stroke: black;
    stroke-width: 3;
  }

  ::ng-deep .test2 {
    fill-opacity: 0.5;
  }
```

Please let me know if this doesn't resolve the issue.

**Comment by oduvanka** [comment]
Thank you, problem solved :)
