### ISSUE TITLE
draw a grid using a svg [FEATURE]

### ISSUE THREAD

**Issue by oduvanka** [vvaldersteins/ngx-svg#8]
**Is your feature request related to a problem? Please describe.**
Now a [PNG ](https://github.com/vvaldersteins/ngx-svg/blob/master/src/assets/images/grid.png) is used to create the grid. Because of this, I can't change the grid color or size

**Describe the solution you'd like**

Example 1
[SVG can do this using patterns](https://stackoverflow.com/questions/14208673/how-to-draw-grid-using-html5-and-canvas-or-svg)

Example 2
[svg.js, SVG.Pattern](https://svgjs.com/docs/3.0/shape-elements/#svg-pattern)
```
var draw = SVG().addTo('body').size(500, 130)
var pattern = draw.pattern(20, 20, function(add) {
  add.rect(20,20).fill('#000')
  add.rect(19,19).fill('#fff')
})
draw.rect(100, 100).move(20, 20).fill(pattern)
```

**Comment by vvaldersteins** [comment]
Hi @oduvanka .

This has been implemented in [v1.0.1](https://github.com/vvaldersteins/ngx-svg/releases/tag/v1.0.1). Please see the updated documentation and demo page on how to use it.

Please let me know if you experience any issues.
