### ISSUE TITLE
[FEATURE] SVG Groups

### ISSUE THREAD

**Issue by KiransHub** [vvaldersteins/ngx-svg#9]
There does not seem to be an element for group which is quite an important svg element. 

I could use the group as a nice place to put an *ng-for where I want to show many elements over and over again. 

I think groups are an important svg element and should be considered.

**Comment by KiransHub** [comment]
I managed to get around this by using <svg:g>

**Comment by KiransHub** [comment]
Perhaps an update of the readme would be enough to get by?

**Comment by FairyAme** [comment]
I think so ,Maybe no g element will block me off  using this powerful Module

**Comment by KiransHub** [comment]
> I think so ,Maybe no g element will block me off using this powerful Module

You can still use <svg:g> to be honest I ended up taking this approach and not using the module but that's only because I probably didn't know all of the benefits that it has to offer.
